version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_DEFAULT_USER=xmasuser
      - RABBITMQ_DEFAULT_PASS=xmaspassword
    networks:
        - xmas
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    image: ${DOCKER_REGISTRY-}xmas-api
    build:
      context: ../
      dockerfile: Back/XmasHack.API/Dockerfile
    volumes:
      - ../documents:/documents
    ports:
      - '8888:80'

  nginx-static:
      container_name: nginx-static
      image: nginx-static
      build:
          context: ../
          dockerfile: nginx/Dockerfile
      restart: always
      ports:
          - "8005:80"
          
  ml_worker:
    build: ../Back/ML_Worker
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - mqtt.env
      - TORCH_HOME=/ml/.cache/torch
    networks:
      - xmas
    volumes:
      - ../backend/worker:/app
      - ../databases/models:/models
      - ../ml:/ml
    entrypoint: 
      ./predict_worker.py

networks:
  xmas:
    driver: bridge
